name: xcube-cmems
channels:
  - conda-forge
dependencies:
  # Required
  - copernicusmarine >=2.1.1
  - xcube >=1.9.1
  - numpy <2.0.0 # xarray<2024.7.0 with numpy>=2.0.0 leads to inconsistent results
  - xarray >=2024.7.0
  - pandas
  # for testing
  - black
  - flake8
  - mock
  - pytest





