name: xcube-cmems
channels:
  - conda-forge
dependencies:
  # Required
  - copernicusmarine >=1.0.10
  - numpy
  - pandas
  - xarray
  - xcube>=1.5.1
  # for testing
  - black
  - flake8
  - mock
  - pathlib
  - pytest





