name: xcube-cmems
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - copernicusmarine >=1.0.10
  - numpy
  - pandas
  - xarray
  - xcube >=0.12.1
  - zarr
  # for testing
  - black
  - flake8
  - mock
  - pathlib
  - pytest





