name: xcube-cmems
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.10
  # Required
  - copernicusmarine >=2.1.1
  - xcube >=1.9.1
  - numpy >=2.0.0 # to avoid inconsistent results with copernicusmarine package
  - pandas
  # for testing
  - black
  - flake8
  - mock
  - pytest
  - pytest-cov



