name: Build

on:
  push:
  release:
    types: [published]
env:
  CMEMS_USERNAME: ${{ secrets.CMEMS_USERNAME }}
  CMEMS_PASSWORD: ${{ secrets.CMEMS_PASSWORD }}

jobs:
  unittest:
    runs-on: ubuntu-latest
    env:
      NUMBA_DISABLE_JIT: 1
    steps:
      - name: checkout xcube-cmems
        uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
            micromamba-version: '1.4.8-0'
            environment-file: environment.yml
            init-shell: >-
                bash
            # Don't cache the environment, since this would prevent us from
            # catching test failures caused by updated versions of dependencies.
            cache-environment: false
            post-cleanup: 'all'

      -   name: setup-xcube-cmems
          shell: bash -l {0}
          run: |
              conda info
              conda list
              pip install -e .

      -   name: unittest-xcube
          shell: bash -l {0}
          run: |
              pytest --cov=xcube_cmems --cov-report=xml
          
